name: eth2eth@v0.3
on: [push, pull_request]

env:
  CACHE_BIN_RELAYER_KEY: bin-relayer
  CACHE_BIN_RELAYER_PATH: ./build/yrly
  CACHE_DOCKER_ETHEREUM_KEY: docker-ethereum
  CACHE_DOCKER_ETHEREUM_DIR: /tmp/ethereum

jobs:
  eth2eth-test:
    name: eth2eth-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.sha }}
          check-regexp: '(relayer|ethereum)-build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-regexp: '(relayer|ethereum)-build'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Restore relayer binary cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_BIN_RELAYER_PATH }}
          key: ${{ runner.os }}-${{ env.CACHE_BIN_RELAYER_KEY }}-${{ hashFiles('relayer/**', 'go.sum') }}
      - name: Restore Ethereum docker image cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_DOCKER_ETHEREUM_DIR }}
          key: ${{ runner.os }}-${{ env.CACHE_DOCKER_ETHEREUM_KEY }}-${{ hashFiles('tests/chains/ethereum/**', '!**/.git/**') }}
      - name: Load Ethereum docker images
        working-directory: ./tests/scripts
        run: |
          ./load_docker_images $CACHE_DOCKER_ETHEREUM_DIR ethereum-ganache0:latest ethereum-ganache1:latest
      - name: Run Test
        working-directory: ./tests/cases/eth2eth
        run: |
          make network
          make test
          make network-down
